echo "este es mi primer hola mundo desde un job de Jenkins "
echo " "
echo "Este es mi primer triger a no veas como me costo el jijo"
echo " "
echo "Este es la primera ejecucion del triger tra la eliminacion del contenedor"
